import type { Week } from './hours'

export const BIZ = {
  name: 'B&N Design Associate Sdn. Bhd.',
  short: 'B&N Design',
  office: '+60 3-4142 6344', officeTel: '+60341426344',
  mobile: '+60 16-618 5266', mobileTel: '+60166185266', wa: '60166185266',
  fax: '+60 3-4142 6346',
  email: 'adm.bnndesign@gmail.com',
  address: '38-1, Jalan Rampai Niaga 4, Rampai Business Park, 53300 Kuala Lumpur',
  maps: 'https://www.google.com/maps/search/?api=1&query=B%26N+Design+Associate+Sdn+Bhd%2C+38-1+Jalan+Rampai+Niaga+4%2C+53300+Kuala+Lumpur',
  directions: 'https://www.google.com/maps/dir/?api=1&destination=38-1+Jalan+Rampai+Niaga+4%2C+Rampai+Business+Park%2C+53300+Kuala+Lumpur',
  facebook: 'https://www.facebook.com/BN-Design-Associate-Sdn-Bhd-102238008868962/',
}

/** Mon–Fri 9:00–18:00 (index 0 = Sunday) */
export const WEEK: Week = [null, [540, 1080], [540, 1080], [540, 1080], [540, 1080], [540, 1080], null]

export type Sector = 'h' | 'g' | 'r' | 'w' | 's' | 'o'
export type Award = 'platinum' | 'gold' | 'silver'
/** From the project list on bnndesign.com (duplicates removed, spelling tidied). Groupings follow the project names. */
export const PROJECTS: { n: string; s: Sector; a?: Award }[] = [
  { n: 'Mercure Hotel, Miri', s: 'h', a: 'gold' },
  { n: 'Mercure Hotel Restaurant, Miri', s: 'h' },
  { n: 'CavaKita Rooftop Bar, Mercure Hotel Miri', s: 'h', a: 'silver' },
  { n: 'The Minh Sales Gallery, Mont Kiara', s: 'g', a: 'platinum' },
  { n: 'The Minh Type B, Mont Kiara', s: 'g' },
  { n: 'The Minh Type D, Mont Kiara', s: 'g' },
  { n: 'Arunya@KL North Sales Gallery', s: 'g' },
  { n: 'Arunya@KL North, Type C', s: 'g' },
  { n: 'Arunya@KL North, Type D', s: 'g' },
  { n: 'Arunya Sales Gallery', s: 'g' },
  { n: 'Paya Bunga Hotel, Kuala Terengganu', s: 'h' },
  { n: 'Matterhorn Restaurant & Bar, Damansara City Mall', s: 'h' },
  { n: 'Party Play Cafe', s: 'h' },
  { n: 'The Oval KLCC, Parts 1–3', s: 'r' },
  { n: 'Seri Riana Residences', s: 'r' },
  { n: 'IJM Seri Riana Show House', s: 'g' },
  { n: 'Lake Point Type LL', s: 'g' },
  { n: 'Lake Point Type CC', s: 'g' },
  { n: 'Lake Point Residence', s: 'o' },
  { n: 'Lake Point Cyberjaya', s: 'o' },
  { n: 'Utama 9 Residences', s: 'r' },
  { n: 'Banyan Tree Residences', s: 'r' },
  { n: 'The Nest Gallery', s: 'g' },
  { n: 'The Nest Residence', s: 'r' },
  { n: 'MK28 Residences', s: 'r' },
  { n: 'Tropics Condominium', s: 'r' },
  { n: 'Sentrio Suites Gallery', s: 'g' },
  { n: 'Sentrio Suite 1', s: 'r' },
  { n: 'Sentrio Suite 2', s: 'r' },
  { n: 'KL Pavilion Residence', s: 'r' },
  { n: "LBS D'Island Residence Show House", s: 'g' },
  { n: 'Hua Yang Head Office', s: 'w' },
  { n: 'SteriPack Asia Corporate Office', s: 'w' },
  { n: 'Farmcochem Corporate Office', s: 'w' },
  { n: 'SwissAire Show Room', s: 's' },
  { n: 'Circle Art of Massage', s: 's' },
  { n: 'E. Excel, Penang', s: 'o' },
  { n: 'EkoCheras Suite', s: 'o' },
  { n: 'Desa Park City 138', s: 'o' },
  { n: 'Kiara Hill', s: 'o' },
  { n: 'Kiara View', s: 'o' },
  { n: 'Ara Hill', s: 'o' },
  { n: 'Idaman Hill', s: 'o' },
  { n: 'Casa Rimba', s: 'o' },
  { n: 'KL Pavilion', s: 'o' },
]

export const CLIENTS: [string, string][] = [
  ['IJM Infra Sdn Bhd', 'Sri Riana Show House'],
  ['Hua Yang Group Berhad', 'Head office · Sentrio Suites'],
  ['LBS Bina Group Berhad', "D'Island Residence Show House"],
  ['Eastern Corridor Sdn Bhd', 'Lake Point Residence Gallery'],
  ['Sierra Cube Sdn Bhd', 'The Nest Gallery & Residence'],
  ['Mercure Hotels, Miri', 'Hotel, restaurant & rooftop bar'],
  ['Paya Bunga Hotel', 'Kuala Terengganu'],
  ['Matterhorn Restaurant & Bar', 'Damansara City Mall'],
  ['SteriPack Asia Sdn Bhd', 'Corporate office'],
  ['Farmcochem Sdn Bhd', 'Corporate office'],
  ['Extra Excel (M) Sdn Bhd', 'E. Excel, Penang'],
  ['Kluang Station', ''],
]

export const ROOM_IDS = ['atoti', 'belian', 'terabai', 'rooms', 'cavakita'] as const
export type RoomId = (typeof ROOM_IDS)[number]

const en = {
  meta: {
    title: 'B&N Design Associate | Award-winning Interior Design & Build, Kuala Lumpur · Since 2006',
    desc: 'Interior design & build since 2006: hotels, sales galleries, show units, offices and homes. Gold, Silver & Platinum winner, Atap Design Award 2023. Rampai Business Park, KL.',
  },
  langLabel: 'BM', langAria: 'BM · Tukar ke Bahasa Melayu',
  a11y: { skip: 'Skip to content', main: 'Main', menuOpen: 'Open menu', menuClose: 'Close menu', mobile: 'Site menu', fab: 'WhatsApp B&N Design', rooms: 'Mercure Hotel Miri spaces', filter: 'Filter projects by type', bar: 'Quick contact', prev: 'Previous space', next: 'Next space', ledger: 'Atap Design Award 2023 results' },
  nav: [['work', 'Mercure Miri'], ['projects', 'Projects'], ['services', 'Services'], ['awards', 'Recognition'], ['brief', 'Brief'], ['contact', 'Contact']] as [string, string][],
  waCta: 'WhatsApp', call: 'Call', briefCta: 'Brief',
  waMsg: "Hi B&N Design, I'd like to discuss an interior design project.",
  illustrative: 'Illustrative stock photo · not a B&N project',
  status: { open: 'Office open', closes: 'until 6 PM', closed: 'Office closed', opens: 'Mon–Fri, 9 AM – 6 PM', checking: 'Mon–Fri, 9 AM – 6 PM' },
  hero: {
    eyebrow: 'Interior design & build · Kuala Lumpur · Since 2006',
    h1a: 'Award-winning interiors,',
    h1b: 'designed and built.',
    sub: 'Hotels, sales galleries, offices and homes, from Kuala Lumpur to Miri. One studio, one contract, from first concept to handover.',
    cta: 'Start a project brief', cta2: 'Read the Mercure Miri story',
    plaquesTitle: 'Atap Design Award 2023',
    proof: 'Atap Design Award 2023 · Platinum · Gold · Silver',
  },
  plaques: [
    { tier: 'Platinum', project: 'The Minh Sales Gallery', place: 'Mont Kiara' },
    { tier: 'Gold', project: 'Mercure Hotel Miri', place: 'Sarawak' },
    { tier: 'Silver', project: 'CavaKita Rooftop Bar', place: 'Mercure Hotel Miri' },
    { tier: 'Outstanding Designer', project: 'B&N Design Associate', place: '' },
  ],
  stats: [['2006', 'Founded in Kuala Lumpur'], ['40+', 'Projects on B&N’s register'], ['KL → Miri', 'Klang Valley, Penang, Terengganu, Sarawak']] as [string, string][],
  clients: { eyebrow: 'Selected clients', note: 'From B&N’s client list.' },
  work: {
    eyebrow: 'Featured project · Gold, Atap Design Award 2023',
    title: 'Mercure Hotel Miri: Sarawak, room by room.',
    quote: '“The rationale behind this design is to honor Sarawak’s cultural heritage and its profound relationship with nature.”',
    quoteBy: 'B&N Design, project notes',
    concept: 'The concept merges the traditions of Sarawak’s indigenous peoples with its natural environment: tribal patterns, handwoven textiles and carved wood alongside bamboo, rattan and stone, in earthy colours and organic shapes.',
    pick: 'Choose a space',
    rooms: {
      atoti: { name: 'Atoti', kind: 'Lobby', text: 'The lobby draws on cave imagery, with imaginative stalactites and swiftlets overhead: a welcoming space where guests can relax and connect.', tags: ['Cave imagery', 'Stalactites', 'Swiftlets'] },
      belian: { name: 'Belian', kind: 'Restaurant', text: 'The restaurant honours Borneo’s forests with balanced designs, and dining that ranges from quick bites to fine dining, adapting to guests through the day.', tags: ['Borneo’s forests', 'All-day dining', 'Balanced design'] },
      terabai: { name: 'Terabai', kind: 'Ballroom', text: 'Inspired by the Iban warrior’s shield and designed for joyful celebrations.', tags: ['Iban shield', 'Celebration', 'Pattern'] },
      rooms: { name: 'Guest rooms', kind: 'Rooms', text: 'Colours and textures that reflect Miri’s sea and rainforest, with faux reptile-skin headboards and rugs inspired by Tusan Cliff.', tags: ['Sea & rainforest', 'Tusan Cliff rugs', 'Textured headboards'] },
      cavakita: { name: 'CavaKita', kind: 'Rooftop bar · Silver, Atap 2023', text: 'Inspired by the region’s caves, with a forest tunnel from the lift. It comes alive at sunset, and a short-tailed macaque “DJ” nods to the story of Aki Bugek.', tags: ['Niah Caves', 'Forest tunnel', 'Sunset'] },
    } as Record<RoomId, { name: string; kind: string; text: string; tags: string[] }>,
    illus: 'Abstract illustration based on B&N’s design notes, not a project photo.',
    swipe: 'Swipe through the five spaces',
  },
  projects: {
    eyebrow: 'Selected work',
    title: 'Forty-plus interiors since 2006.',
    sub: 'Three award winners first, then the full register from B&N’s own project list, grouped by type.',
    winners: 'Atap Design Award 2023',
    register: 'Project register',
    story: 'Read the story',
    sectors: { g: 'Sales gallery', h: 'Hotel & F&B' } as Record<string, string>,
    filters: { all: 'All', h: 'Hotels & F&B', g: 'Galleries & show units', r: 'Residences', w: 'Workplaces', s: 'Retail & wellness', o: 'Other' } as Record<'all' | Sector, string>,
    awards: { platinum: 'Platinum', gold: 'Gold', silver: 'Silver' } as Record<Award, string>,
    count: 'projects', showAll: 'Show all projects', showLess: 'Show fewer',
    ask: 'Want to see projects like yours? Ask us for photos on WhatsApp.',
  },
  services: {
    eyebrow: 'What B&N does',
    title: 'One contract. One point of responsibility.',
    items: [
      ['Interior design & build consultation', 'B&N is the client’s only point of contact, simplifying the whole process with contractors and suppliers.'],
      ['Renovation & construction', 'Design, build and construct under one roof: the single point of responsibility sits with B&N, with quality control and project management built in.'],
      ['Turnkey solutions', 'Turnkey delivery that offers a faster response: you receive a finished space, ready to use.'],
      ['Corporate interior identity', 'Developing and implementing corporate interior identities and branding, from logo and print to display graphics.'],
    ] as [string, string][],
    whyTitle: 'Why clients choose B&N',
    why: [
      ['Creative & practical', 'Committed, creative, practical and able to work within your budget.'],
      ['Working knowledge', 'Strong working knowledge of local practices, contractors and suppliers.'],
      ['High quality', 'Regular trade contractors and suppliers understand the expectation for high quality.'],
      ['Management skill', 'Project and construction management to deliver on time and within cost.'],
    ] as [string, string][],
    benefitsTitle: 'Why design & build',
    benefits: ['All team members work under the same contract, so projects move faster.', 'The expected cost is defined early, which helps keep construction on budget.', 'Closer collaboration means fewer revisions and errors.'],
    photoAlt: 'Timber-panelled lift lobby with soft lighting and a patterned carpet',
    network: 'B&N works on a networking basis: specialist assignments are out-panelled to other interior design specialists while B&N controls the principal costs.',
  },
  awards: {
    eyebrow: 'Recognition & press',
    title: 'Two decades on the record.',
    items: [
      ['2023', 'Atap Design Award 2023', 'Platinum, Gold and Silver, plus Outstanding Designer'],
      ['2011', 'ROOM, February 2011', '“A Dash of Lavish”'],
      ['2011', 'Reno & Decor, June 2011', 'Magazine feature'],
      ['2010', 'Designer Concept Vol. 6, June 2010', 'Magazine feature'],
      ['2009', 'Designer of the Year 2009', 'Designer Concept magazine, December 2009'],
      ['2009', 'Designer Concept, January 2009', '“The doctrine of simplicity in an office space”'],
      ['2006', 'B&N Design founded', 'Kuala Lumpur'],
    ] as [string, string, string][],
  },
  brief: {
    eyebrow: 'Project brief',
    title: 'Draw up your brief in a minute.',
    sub: 'Tap what you know. It fills in a drawing title block that you can send by WhatsApp or email.',
    type: 'Project type', types: ['Hotel / F&B', 'Sales gallery / show unit', 'Office', 'Residence', 'Retail / other'],
    scope: 'Scope', scopes: ['Design consultation', 'Design & build', 'Turnkey', 'Not sure yet'],
    when: 'Timeline', whens: ['As soon as possible', 'In 3–6 months', 'In 6–12 months', 'Just planning'],
    loc: 'Location', locPh: 'e.g. Mont Kiara, KL',
    area: 'Approx. area (sq ft)', areaPh: 'e.g. 2,400',
    name: 'Your name', company: 'Company (optional)',
    sheet: 'Brief', blank: '—', sqft: 'sq ft',
    fields: { project: 'Project', scope: 'Scope', loc: 'Location', area: 'Area', when: 'Timeline', client: 'Client', date: 'Date', sheet: 'Sheet' },
    wa: 'Send on WhatsApp', mail: 'Send by email',
    hint: 'Office line 03-4142 6344, Monday to Friday, 9 AM – 6 PM.',
    msgHi: "Hi B&N Design, here's a project brief:",
    msgEnd: 'Could we arrange a call to discuss? Thank you.',
    subject: 'Project brief',
    photoAlt: 'Hands arranging material and colour samples on a desk',
  },
  contact: {
    eyebrow: 'Contact',
    title: 'Rampai Business Park, Kuala Lumpur.',
    office: 'Office', mobile: 'Mobile / WhatsApp', email: 'Email', fax: 'Fax', address: 'Address', hours: 'Office hours', hoursText: 'Monday – Friday, 9 AM – 6 PM',
    maps: 'Google Maps', directions: 'Get directions', facebook: 'Facebook',
  },
  faq: {
    eyebrow: 'Questions',
    title: 'Before we start.',
    items: [
      ['Do you design only, or design and build?', 'Both. B&N offers interior design and build consultation, renovation and construction, and turnkey solutions, with B&N as your single point of contact.'],
      ['What kinds of projects do you take on?', 'Past work includes hotels and restaurants, sales galleries and show units, corporate offices, residences, showrooms and wellness spaces. Tell us about yours and we’ll say honestly whether it’s a fit.'],
      ['Do you work outside Kuala Lumpur?', 'Yes. Past projects include Mercure Hotel Miri in Sarawak, Paya Bunga Hotel in Kuala Terengganu and E. Excel in Penang.'],
      ['Can I see photos of past projects?', 'Message us with your project type on WhatsApp or by email and we’ll share relevant work.'],
      ['When can I visit the office?', 'Monday to Friday, 9 AM to 6 PM, at 38-1 Jalan Rampai Niaga 4, Rampai Business Park. Please message or call ahead.'],
      ['Can we talk in Bahasa Melayu?', 'Of course. Write to us in Bahasa Melayu or English.'],
    ] as [string, string][],
  },
  footer: {
    tagline: 'Interior design & build · Kuala Lumpur · Since 2006',
    toTop: 'Back to top',
    note: 'Illustrations are abstract interpretations of B&N’s published design notes; project details and copy are from bnndesign.com. The photo is an illustrative stock image (Unsplash), not a B&N project.',
    pitch: 'Website concept prepared for this studio. Not an official site yet — open to making it yours.',
    pitchLink: 'Talk to the designer',
    rights: 'All trademarks belong to their owners.',
  },
}

export type Content = typeof en

const ms: Content = {
  meta: {
    title: 'B&N Design Associate | Reka Bentuk & Bina Dalaman Pemenang Anugerah, Kuala Lumpur · Sejak 2006',
    desc: 'Reka bentuk & bina dalaman sejak 2006: hotel, galeri jualan, unit pameran, pejabat dan kediaman. Pemenang Emas, Perak & Platinum, Atap Design Award 2023. Rampai Business Park, KL.',
  },
  langLabel: 'EN', langAria: 'EN · Switch to English',
  a11y: { skip: 'Langkau ke kandungan', main: 'Utama', menuOpen: 'Buka menu', menuClose: 'Tutup menu', mobile: 'Menu laman', fab: 'WhatsApp B&N Design', rooms: 'Ruang Mercure Hotel Miri', filter: 'Tapis projek mengikut jenis', bar: 'Hubungan pantas', prev: 'Ruang sebelumnya', next: 'Ruang seterusnya', ledger: 'Keputusan Atap Design Award 2023' },
  nav: [['work', 'Mercure Miri'], ['projects', 'Projek'], ['services', 'Servis'], ['awards', 'Pengiktirafan'], ['brief', 'Ringkasan'], ['contact', 'Hubungi']],
  waCta: 'WhatsApp', call: 'Telefon', briefCta: 'Ringkasan',
  waMsg: 'Hai B&N Design, saya ingin berbincang tentang projek reka bentuk dalaman.',
  illustrative: 'Foto stok ilustrasi · bukan projek B&N',
  status: { open: 'Pejabat dibuka', closes: 'hingga 6 petang', closed: 'Pejabat ditutup', opens: 'Isn–Jum, 9 pagi – 6 petang', checking: 'Isn–Jum, 9 pagi – 6 petang' },
  hero: {
    eyebrow: 'Reka bentuk & bina dalaman · Kuala Lumpur · Sejak 2006',
    h1a: 'Dalaman pemenang anugerah,',
    h1b: 'direka dan dibina.',
    sub: 'Hotel, galeri jualan, pejabat dan kediaman, dari Kuala Lumpur hingga Miri. Satu studio, satu kontrak, dari konsep pertama hingga serahan kunci.',
    cta: 'Mulakan ringkasan projek', cta2: 'Baca kisah Mercure Miri',
    plaquesTitle: 'Atap Design Award 2023',
    proof: 'Atap Design Award 2023 · Platinum · Emas · Perak',
  },
  plaques: [
    { tier: 'Platinum', project: 'The Minh Sales Gallery', place: 'Mont Kiara' },
    { tier: 'Emas', project: 'Mercure Hotel Miri', place: 'Sarawak' },
    { tier: 'Perak', project: 'CavaKita Rooftop Bar', place: 'Mercure Hotel Miri' },
    { tier: 'Pereka Cemerlang', project: 'B&N Design Associate', place: '' },
  ],
  stats: [['2006', 'Ditubuhkan di Kuala Lumpur'], ['40+', 'Projek dalam daftar B&N'], ['KL → Miri', 'Lembah Klang, Pulau Pinang, Terengganu, Sarawak']],
  clients: { eyebrow: 'Antara pelanggan', note: 'Daripada senarai pelanggan B&N.' },
  work: {
    eyebrow: 'Projek pilihan · Emas, Atap Design Award 2023',
    title: 'Mercure Hotel Miri: Sarawak, ruang demi ruang.',
    quote: '“The rationale behind this design is to honor Sarawak’s cultural heritage and its profound relationship with nature.”',
    quoteBy: 'B&N Design, nota projek (asal dalam bahasa Inggeris)',
    concept: 'Konsep ini menggabungkan tradisi masyarakat peribumi Sarawak dengan alam semula jadinya: corak etnik, tekstil tenunan tangan dan ukiran kayu bersama buluh, rotan dan batu, dalam warna tanah dan bentuk organik.',
    pick: 'Pilih ruang',
    rooms: {
      atoti: { name: 'Atoti', kind: 'Lobi', text: 'Lobi ini mengambil ilham daripada gua, dengan stalaktit dan burung walit di atas kepala: ruang mesra untuk tetamu berehat dan berhubung.', tags: ['Imej gua', 'Stalaktit', 'Burung walit'] },
      belian: { name: 'Belian', kind: 'Restoran', text: 'Restoran ini memuliakan hutan Borneo dengan reka bentuk yang seimbang, dan hidangan dari snek ringkas hingga santapan mewah, menyesuaikan keperluan tetamu sepanjang hari.', tags: ['Hutan Borneo', 'Santapan sepanjang hari', 'Reka bentuk seimbang'] },
      terabai: { name: 'Terabai', kind: 'Dewan bankuet', text: 'Diilhamkan oleh perisai pahlawan Iban dan direka untuk sambutan yang meriah.', tags: ['Perisai Iban', 'Sambutan', 'Corak'] },
      rooms: { name: 'Bilik tetamu', kind: 'Bilik', text: 'Warna dan tekstur yang mencerminkan laut dan hutan hujan Miri, dengan kepala katil bertekstur kulit reptilia tiruan dan permaidani yang diilhamkan oleh Tebing Tusan.', tags: ['Laut & hutan hujan', 'Permaidani Tebing Tusan', 'Kepala katil bertekstur'] },
      cavakita: { name: 'CavaKita', kind: 'Bar bumbung · Perak, Atap 2023', text: 'Diilhamkan oleh gua-gua di rantau ini, dengan terowong hutan dari lif. Ia hidup ketika matahari terbenam, dan “DJ” kera ekor pendek mengingatkan kisah Aki Bugek.', tags: ['Gua Niah', 'Terowong hutan', 'Senja'] },
    },
    illus: 'Ilustrasi abstrak berdasarkan nota reka bentuk B&N, bukan foto projek.',
    swipe: 'Leret untuk lihat lima ruang',
  },
  projects: {
    eyebrow: 'Karya pilihan',
    title: 'Lebih empat puluh dalaman sejak 2006.',
    sub: 'Tiga pemenang anugerah dahulu, kemudian daftar penuh daripada senarai projek B&N sendiri, dikumpul mengikut jenis.',
    winners: 'Atap Design Award 2023',
    register: 'Daftar projek',
    story: 'Baca kisahnya',
    sectors: { g: 'Galeri jualan', h: 'Hotel & F&B' },
    filters: { all: 'Semua', h: 'Hotel & F&B', g: 'Galeri & unit pameran', r: 'Kediaman', w: 'Tempat kerja', s: 'Runcit & kesejahteraan', o: 'Lain-lain' },
    awards: { platinum: 'Platinum', gold: 'Emas', silver: 'Perak' },
    count: 'projek', showAll: 'Tunjuk semua projek', showLess: 'Tunjuk kurang',
    ask: 'Mahu lihat projek seperti anda? Minta gambar di WhatsApp.',
  },
  services: {
    eyebrow: 'Apa yang B&N lakukan',
    title: 'Satu kontrak. Satu pihak bertanggungjawab.',
    items: [
      ['Konsultasi reka bentuk & bina dalaman', 'B&N ialah satu-satunya titik hubungan pelanggan, memudahkan keseluruhan proses dengan kontraktor dan pembekal.'],
      ['Ubah suai & pembinaan', 'Reka, bina dan siapkan di bawah satu bumbung: tanggungjawab tunggal terletak pada B&N, dengan kawalan kualiti dan pengurusan projek.'],
      ['Penyelesaian turnkey', 'Penyerahan turnkey dengan tindak balas lebih pantas: anda menerima ruang yang siap untuk digunakan.'],
      ['Identiti dalaman korporat', 'Membangun dan melaksanakan identiti dalaman korporat dan penjenamaan, dari logo dan cetakan hingga grafik paparan.'],
    ],
    whyTitle: 'Mengapa pelanggan memilih B&N',
    why: [
      ['Kreatif & praktikal', 'Komited, kreatif, praktikal dan boleh bekerja mengikut bajet anda.'],
      ['Pengetahuan setempat', 'Pengetahuan kukuh tentang amalan, kontraktor dan pembekal tempatan.'],
      ['Kualiti tinggi', 'Kontraktor dan pembekal tetap memahami jangkaan kualiti yang tinggi.'],
      ['Kemahiran pengurusan', 'Pengurusan projek dan pembinaan untuk siap tepat masa dan dalam kos.'],
    ],
    benefitsTitle: 'Mengapa reka & bina',
    benefits: ['Semua ahli pasukan di bawah kontrak yang sama, jadi projek bergerak lebih pantas.', 'Anggaran kos ditetapkan awal, membantu pembinaan kekal dalam bajet.', 'Kerjasama rapat bermakna kurang semakan dan kesilapan.'],
    photoAlt: 'Lobi lif berpanel kayu dengan pencahayaan lembut dan permaidani bercorak',
    network: 'B&N beroperasi secara rangkaian: tugasan pakar diserahkan kepada pakar reka bentuk dalaman lain sementara B&N mengawal kos utama.',
  },
  awards: {
    eyebrow: 'Pengiktirafan & media',
    title: 'Dua dekad dalam rekod.',
    items: [
      ['2023', 'Atap Design Award 2023', 'Platinum, Emas dan Perak, serta Pereka Cemerlang'],
      ['2011', 'ROOM, Februari 2011', '“A Dash of Lavish”'],
      ['2011', 'Reno & Decor, Jun 2011', 'Paparan majalah'],
      ['2010', 'Designer Concept Vol. 6, Jun 2010', 'Paparan majalah'],
      ['2009', 'Designer of the Year 2009', 'Majalah Designer Concept, Disember 2009'],
      ['2009', 'Designer Concept, Januari 2009', '“The doctrine of simplicity in an office space”'],
      ['2006', 'B&N Design ditubuhkan', 'Kuala Lumpur'],
    ],
  },
  brief: {
    eyebrow: 'Ringkasan projek',
    title: 'Sediakan ringkasan anda dalam seminit.',
    sub: 'Pilih apa yang anda tahu. Ia mengisi blok tajuk lukisan yang boleh anda hantar melalui WhatsApp atau e-mel.',
    type: 'Jenis projek', types: ['Hotel / F&B', 'Galeri jualan / unit pameran', 'Pejabat', 'Kediaman', 'Runcit / lain-lain'],
    scope: 'Skop', scopes: ['Konsultasi reka bentuk', 'Reka & bina', 'Turnkey', 'Belum pasti'],
    when: 'Tempoh', whens: ['Secepat mungkin', 'Dalam 3–6 bulan', 'Dalam 6–12 bulan', 'Masih merancang'],
    loc: 'Lokasi', locPh: 'cth. Mont Kiara, KL',
    area: 'Anggaran keluasan (kaki persegi)', areaPh: 'cth. 2,400',
    name: 'Nama anda', company: 'Syarikat (pilihan)',
    sheet: 'Ringkasan', blank: '—', sqft: 'kaki persegi',
    fields: { project: 'Projek', scope: 'Skop', loc: 'Lokasi', area: 'Keluasan', when: 'Tempoh', client: 'Pelanggan', date: 'Tarikh', sheet: 'Helaian' },
    wa: 'Hantar di WhatsApp', mail: 'Hantar melalui e-mel',
    hint: 'Talian pejabat 03-4142 6344, Isnin hingga Jumaat, 9 pagi – 6 petang.',
    msgHi: 'Hai B&N Design, ini ringkasan projek saya:',
    msgEnd: 'Boleh kita atur panggilan untuk berbincang? Terima kasih.',
    subject: 'Ringkasan projek',
    photoAlt: 'Tangan menyusun sampel bahan dan warna di atas meja',
  },
  contact: {
    eyebrow: 'Hubungi',
    title: 'Rampai Business Park, Kuala Lumpur.',
    office: 'Pejabat', mobile: 'Mudah alih / WhatsApp', email: 'E-mel', fax: 'Faks', address: 'Alamat', hours: 'Waktu pejabat', hoursText: 'Isnin – Jumaat, 9 pagi – 6 petang',
    maps: 'Google Maps', directions: 'Dapatkan arah', facebook: 'Facebook',
  },
  faq: {
    eyebrow: 'Soalan',
    title: 'Sebelum kita bermula.',
    items: [
      ['Adakah anda mereka sahaja, atau mereka dan membina?', 'Kedua-duanya. B&N menawarkan konsultasi reka bentuk dan bina dalaman, ubah suai dan pembinaan, serta penyelesaian turnkey, dengan B&N sebagai satu-satunya titik hubungan anda.'],
      ['Projek jenis apa yang anda ambil?', 'Kerja lepas termasuk hotel dan restoran, galeri jualan dan unit pameran, pejabat korporat, kediaman, bilik pameran dan ruang kesejahteraan. Ceritakan projek anda dan kami akan beritahu dengan jujur sama ada ia sesuai.'],
      ['Adakah anda bekerja di luar Kuala Lumpur?', 'Ya. Projek lepas termasuk Mercure Hotel Miri di Sarawak, Paya Bunga Hotel di Kuala Terengganu dan E. Excel di Pulau Pinang.'],
      ['Boleh saya lihat gambar projek lepas?', 'Mesej kami jenis projek anda di WhatsApp atau e-mel dan kami akan kongsikan kerja yang berkaitan.'],
      ['Bila boleh saya melawat pejabat?', 'Isnin hingga Jumaat, 9 pagi hingga 6 petang, di 38-1 Jalan Rampai Niaga 4, Rampai Business Park. Sila mesej atau hubungi dahulu.'],
      ['Boleh kita berbincang dalam Bahasa Melayu?', 'Sudah tentu. Tulis kepada kami dalam Bahasa Melayu atau bahasa Inggeris.'],
    ],
  },
  footer: {
    tagline: 'Reka bentuk & bina dalaman · Kuala Lumpur · Sejak 2006',
    toTop: 'Kembali ke atas',
    note: 'Ilustrasi ialah tafsiran abstrak nota reka bentuk B&N yang diterbitkan; butiran projek dan teks daripada bnndesign.com. Foto ialah imej stok ilustrasi (Unsplash), bukan projek B&N.',
    pitch: 'Konsep laman web disediakan untuk studio ini. Bukan laman rasmi lagi — sedia dijadikan milik anda.',
    pitchLink: 'Hubungi pereka',
    rights: 'Semua tanda dagangan milik pemiliknya.',
  },
}

export const content = { en, ms }
